# Generated by Django 4.1.3 on 2023-02-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=250)),
                ("message", models.TextField()),
                (
                    "upload",
                    models.FileField(
                        blank=True, null=True, upload_to="contact/%Y/%m/%d/"
                    ),
                ),
            ],
        ),
    ]
