# Generated by Django 4.1.3 on 2023-02-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=50, null=True)),
                ("dob", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")], max_length=6
                    ),
                ),
                ("national_id", models.CharField(blank=True, max_length=8, null=True)),
                ("license", models.CharField(max_length=9)),
                ("available", models.BooleanField(default=True)),
            ],
        ),
    ]
