# Generated by Django 4.1.3 on 2023-06-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraddress",
            name="isDefault",
        ),
    ]
