# Generated by Django 4.1.3 on 2022-12-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
