# Generated by Django 4.1.3 on 2023-02-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_ordered",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                ("date_dispatched", models.DateTimeField(blank=True, null=True)),
                ("date_delivered", models.DateTimeField(blank=True, null=True)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Dispatched", "Dispatched"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_phone",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Orders",
            },
        ),
    ]
