# Generated by Django 4.1.3 on 2023-02-26 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
        ("product", "0001_initial"),
        ("rider", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("address", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination",
                to="address.useraddress",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.product"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source",
                to="address.useraddress",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="rider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rider.rider",
            ),
        ),
    ]
